# The following parameters are used to disable the EKF localization when the human is not detected by the kinect sensor

localization_node_name: "/master_computer/human_localization_ekf_se_wr"

timeout: 0.2 # seconds, timeout for waiting for at least one message is received from a sensor topic of the ekf_localization node