image_topic_name: 'rgb/image_raw'

path_to_camera_parameters: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/camera.yml'
path_to_undistorted_camera_parameters: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/camera_undistorted.yml'
path_to_extrinsic_parameters: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/camera_aruco.yml'
path_to_aruco_tags_info: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/aruco_tags_info3.csv'

tf_world_floor_frame_id: 'world_floor'
robot_bases_tf_prefix: ''
robot_bases_tf_postfix: '_base'