image_topic_name: 'rgb/image_raw'  # 'rgb/image_rect_color' # 'rgb/image_raw' 
using_rectified_image: false # Even though a rectified image is used as subsribtion, still the undistorted
# camera parameters are needed. That's because, for example kinect uses 9 distortion parameters internally 
# to undistort raw image. However the aruco detection needs 5 distortion parameters and our own calibration
# parameters provides these 5 distortion parameters (Note that simply ignoring last 4 parameters does not work)
# see: https://scazlab.github.io/azure_setup_guide.html under title "Calibration" for more details.

debug_image_view: true # if true, publishes the detected aruco tags img as a scaled down image(TODO: Does not work properly, but no time to dig in)
debug_image_topic_name: 'debug_aruco_detected_image'
debug_image_scale_percent: 25 # Smaller is more efficient

path_to_camera_parameters: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/camera_1536p.yml'
path_to_undistorted_camera_parameters: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/camera_undistorted_1536p.yml'
path_to_extrinsic_parameters: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/camera_aruco_1536p.yml'
path_to_aruco_tags_info: '~/catkin_ws_assistive/src/assistive_launch/vision_parameters/aruco_tags_info3.csv'

tf_world_floor_frame_id: 'world_floor'
robot_bases_tf_prefix: '' # should end with "_", eg. 'robots_'
robot_bases_tf_postfix: '_base' # should start with "_", eg. '_base'