kinect_body_tracking_data_topic_name: '/body_tracking_data'
tracked_single_joint_name: 'JOINT_WRIST_LEFT' # see https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints, dont forget to add "JOINT_" to the beginning
tf_camera_frame_id: 'depth_camera_link'
