# Set this parameter to use a specific arm on your system    --> 
# serial_number: PJ00000001030703130

# Joint speed limit for joints 1, 2, 3
jointSpeedLimitParameter1: 36 #10

# Joint speed limit for joints 4, 5, 6
jointSpeedLimitParameter2: 48 #20

# payload: [COM COMx COMy COMz]
payload: [0.440, 0.005, 0.06, -0.02] # Right Arm config payload
# payload: [0.0, 0.0, 0.0, 0.0] 

connection_type: USB #Ethernet 

# Ethernet connection parameters
ethernet: {
  local_machine_IP: 192.168.100.100,
  subnet_mask: 255.255.255.0,
  local_cmd_port: 25000,
  local_broadcast_port: 25025
}

#Torque control parameters
#Do not change these parameters unless you want to change torque control behavior
torque_parameters: {
      publish_torque_with_gravity_compensation: false,
      use_estimated_COM_parameters: true,
    # if torque min/max sepecified, all min/max values need to be specified
    #  torque_min: [80, 80, 80, 80, 80, 80, 80],
    #  torque_max: [90, 90, 90, 90, 90, 90, 90],
    # Decides velocity threshold at which robot switches torque to position control (between 0 and 1)
    # safety_factor: 1,
    # COM parameters
    # order [m1,m2,...,m7,x1,x2,...,x7,y1,y2,...y7,z1,z2,...z7]
    # com_parameters: [0,0,0,0,0,0,0, 0,0,0,0,0,0,0, 0,0,0,0,0,0,0, 0,0,0,0,0,0,0]

    # com_parameters: [0.77,0.99,0.8,0.426,0.426,1.08,0,   0,-0.322,0,0,0,0,0,   -0.097,0,-0.0016,0.0277,0.0277,0,0,    0.002,0.0158,-0.0169,0.016,0.016,-0.1047,0] # JACO 2, use_estimated_COM_parameters: false, MANUAL, size 42, default
    
    # com_parameters: [1.2638, -0.017692, -0.00290315, -1.11705, 0.00341232, 0.543942, -0.00114688, 0.177014, -0.00155855, -0.00429202, 0.141195, 0.706983, -0.404671, 0.010646, -0.07242, -0.129179] # JACO 2, use_estimated_COM_parameters: true, OPTIMAL, size 16, default
    com_parameters: [1.23398, -0.0121619, 0.0054745, -1.13275, 0.00312428, 0.56148, -0.00185361, 0.18138, -0.00592868, -0.00736189, 0.173823, 0.0894881, -0.0736135, -0.0491722, -0.0175228, 0.0320743] # JACO 2, use_estimated_COM_parameters: true, OPTIMAL, size 16, w.out payload
}
