z_height_topic_name: 'TODO'
is_fixed_z: True
tf_mobile_base_frame_id: 'oarbot_silver_base'
tf_laser_scanner_2d_frame_id: 'oarbot_silver_laser_scanner_2d_sensor'

mobile_base2laser_scanner_2d_pose:
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
  position: # in meters
    x: 0.267525
    y: 0.0
    z: 0.2764