robot_cartesian_cmd_vel_topic_name: 'j2n6s300_left_driver/in/cartesian_velocity'

tf_followed_body_joint_frame_name: 'j2n6s300_left_body_JOINT_CLAVICLE_RIGHT' # 'JOINT_HEAD' #'JOINT_WRIST_LEFT' # see https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints, dont forget to add "JOINT_" to the beginning
tf_end_effector_frame_name: 'j2n6s300_left_end_effector'
tf_arm_base_frame_name: 'j2n6s300_left_link_base'

v_p_gain: 3.0 
v_d_gain: 0.0
w_p_gain: 5.0
w_d_gain: 0.0

pub_rate: 110.0 # It is a must to be 100 Hz for Kinova arm