robot_cartesian_cmd_vel_topic_name: 'cmd_vel' # 'j2n6s300_left_driver/in/cartesian_velocity'
robot_cartesian_cmd_vel_msg_type: 'geometry_msgs.msg.Twist' # 'kinova_msgs.msg.PoseVelocity'

tf_followed_body_joint_frame_name: 'j2n6s300_left_body_JOINT_CLAVICLE_RIGHT' # 'JOINT_HEAD' #'JOINT_WRIST_LEFT' # see https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints, dont forget to add "JOINT_" to the beginning
tf_end_effector_frame_name: 'j2n6s300_left_end_effector'
tf_arm_base_frame_name: 'oarbot_silver_base' # 'j2n6s300_left_link_base'

v_p_gain: 3.0 
v_d_gain: 0.0 # Not implemented
w_p_gain: 5.0
w_d_gain: 0.0 # Not implemented

pub_rate: 110.0 # It is a must to be 100 Hz for Kinova arm (If higher kinova can continue to move after the the command sendings stops bcs of the queue size)