z_height_topic_name: 'TODO'
is_fixed_z: True
tf_mobile_base_frame_id: 'oarbot_blue_base'
tf_arm_base_frame_id: 'root_right_arm'

mobile_base2arm_base_pose:
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
  position: # in meters
    x: 0.2
    y: 0.0
    z: 0.7