z_height_topic_name: 'TODO'
is_fixed_z: True
tf_mobile_base_frame_id: 'oarbot_blue_base'
tf_2d_laser_scanner_frame_id: 'oarbot_blue_2d_laser_scanner_sensor'

mobile_base22d_laser_scanner_pose:
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
  position: # in meters
    x: 0.271325
    y: -0.003
    z: 0.2944