in_cmd_vel_topic_name: 'cmd_vel_arm'
in_cmd_vel_topic_type: 'geometry_msgs.msg.Twist'
in_rate: 25.0 # Expected for setting the timeout properly

out_cmd_vel_topic_name: 'j2n6s300_left_driver/in/cartesian_velocity'
out_cmd_vel_topic_type: 'kinova_msgs.msg.PoseVelocity'
out_rate: 100.0