feedback_gain_xy: 3.0
feedback_gain_theta: 1.0

cmd_input_type: 'State2D'
#cmd_input_type: 'Twist'
cmd_input_topic_name: 'desired_state'
#cmd_input_topic_name: '/spacenav/twist/repub'
position_feedback_topic_name: 'position'
control_cmd_publish_topic_name: 'cmd_vel'
frame_name: 'oarbot_blue_qd'

vel_lim_x: 0.1134
vel_lim_y: 0.1134
vel_lim_theta: 0.1514

space_mouse_topic_name: '/tablet/spacenav/joy'
