enable_collision_avoidance: true
toggle_collision_avoidance_service_name: "toggle_collision_avoidance"

enable_collision_avoidance_dynamic: true # dynamic collision avoidance with laser scanner msgs

number_of_robots: 2

in_cmd_vel_topic_name: "cmd_vel_base" # subscribed
out_cmd_vel_topic_name: "cmd_vel_base_safer" # published  

tf_world_frame_id: "world_floor"
tf_mobile_base_frame_id: "oarbot_silver_base"

obs_dist_thres: 0.20 # meter
obs_dist_hard_thres: 0.10 # meter

all_tf_mobile_base_frame_ids: 
  - "oarbot_blue_base"
  - "oarbot_silver_base"

all_mobile_base_frame_coords: # width for expansion in x axis, height for expansion in y axis wrt mobile base frame
  # "oarbot_blue_base"
  - - [ 0.32, 0.29]
    - [-0.45, 0.29]
    - [-0.45,-0.29]
    - [ 0.32,-0.29]
    - [ 0.37, 0.00]
  # "oarbot_silver_base" 
  - - [ 0.32, 0.29]
    - [-0.45, 0.29]
    - [-0.45,-0.29]
    - [ 0.32,-0.29]
    - [ 0.37, 0.00]

# FOR 8th FLOOR LAB
workspace_polygon_coords: # each polygon corner is [x,y] wrt tf_world_frame_id
  - [ 0.0, 0.0]
  - [ 3.7, 0.0]
  - [ 3.7, 5.0]
  - [ 0.4, 5.0]
  - [ 0.4, 3.6]
  - [ 0.0, 3.6]

#  FOR HIGHBAY CAGE
# workspace_polygon_coords: # each polygon corner is [x,y] wrt tf_world_frame_id
#   - [ 0.0, -1.0]
#   - [ 1.9, -1.0]
#   - [ 1.9,  3.7]
#   - [-1.1,  3.7]
#   - [-1.1,  3.05]
#   - [-1.7,  3.05]
#   - [-1.7,  1.1]
#   - [ 0.0,  1.1]

viz_mobile_base_polygon_topic_name_prefix: "viz_oarbot_silver_robots_"
viz_mobile_base_obs_dist_thres_topic_name: "viz_oarbot_silver_base_obs_dist_thres"
viz_mobile_base_obs_dist_hard_thres_topic_name: "viz_oarbot_silver_base_obs_dist_hard_thres"
viz_workspace_polygon_topic_name: "viz_oarbot_silver_workspace_polygon"
viz_out_rate: 100.0 # Hz

laser_obstacles_topic_name: "obstacles"
laser_obstacles_expected_rate: 100.0 # hz, used to define a time out for laser obstacle msgs
line_obstacle_buffer_distance: 0.025