robot_cartesian_cmd_vel_topic_name: 'cmd_vel' # 'j2n6s300_right_driver/in/cartesian_velocity'
robot_cartesian_cmd_vel_msg_type: 'geometry_msgs.msg.Twist' # 'kinova_msgs.msg.PoseVelocity'

tf_followed_body_joint_frame_name: 'j2n6s300_right_body_JOINT_CLAVICLE_LEFT' # 'JOINT_HEAD' #'JOINT_WRIST_LEFT' # see https://docs.microsoft.com/en-us/azure/kinect-dk/body-joints, dont forget to add "JOINT_" to the beginning
tf_end_effector_frame_name: 'j2n6s300_right_end_effector'
tf_robot_base_frame_name: 'oarbot_blue_base' # 'j2n6s300_right_link_base'
tf_arm_base_frame_name: 'j2n6s300_right_link_base'

pub_rate: 110.0 # It is a must to be 100 Hz for Kinova arm (If higher kinova can continue to move after the the command sendings stops bcs of the queue size)

wrench_external_topic_name: 'j2n6s300_right_driver/out/tool_wrench_filtered'
wrench_control_topic_name: 'j2n6s300_right_driver/tool_wrench_control'

enable_body_joint_following: false
enable_admittance: true

position_err_thres: 0.005 # meter # 0.5cm
orientation_err_thres: 0.015 # radian # 5 degrees = 0.09 radians 

K_lin_x: 6.0 # K_lin_x: 0.0 # K_lin_x: 3.0
K_lin_y: 6.0 # K_lin_y: 0.0 # K_lin_y: 3.0
K_lin_z: 6.0 # K_lin_z: 0.0 # K_lin_z: 3.0
K_ang_x: 10.0 # K_ang_x: 0.0 # K_ang_x: 5.0
K_ang_y: 10.0 # K_ang_y: 0.0 # K_ang_y: 5.0
K_ang_z: 10.0 # K_ang_z: 0.0 # K_ang_z: 5.0

D_lin_x: 10.0
D_lin_y: 10.0
D_lin_z: 10.0
D_ang_x: 10.0
D_ang_y: 10.0
D_ang_z: 10.0

K_admittance_lin_x: 0.1
K_admittance_lin_y: 0.1
K_admittance_lin_z: 0.1
K_admittance_ang_x: 3.0
K_admittance_ang_y: 3.0
K_admittance_ang_z: 3.0

M_lin_x: 1.0
M_lin_y: 1.0
M_lin_z: 1.0
M_ang_x: 1.0
M_ang_y: 1.0
M_ang_z: 1.0

# Load admittance control wrt robot base, can be updated by publishing to parameter: wrench_control_topic_name above.
F_lin_x_control: 0.0
F_lin_y_control: 0.0
F_lin_z_control: 0.0
F_ang_x_control: 0.0
F_ang_y_control: 0.0
F_ang_z_control: 0.0

max_lin_acc: 1.0 # m/s^2
max_lin_vel: 0.6 # m/s 

max_ang_acc: 1.0 # rad/s^2
max_ang_vel: 1.5 # Rad/s 