z_height_topic_name: 'TODO'
is_fixed_z: True
tf_mobile_base_frame_id: 'oarbot_silver_base'
tf_arm_base_frame_id: 'root_left_arm'

mobile_base2arm_base_pose:
  orientation:
    x: 0.0
    y: 0.0
    z: 1.0
    w: 0.0
  position: # in meters
    x: 0.275
    y: 0.0
    z: 0.807